Algoritmo "semnome"

Var
pedido:real

Inicio

escreval("digite 1 para mousse, 2 para sorvete, 3 para milkshake e 4 para sunday")
leia(pedido)

escolha pedido
caso 1
escreval ("voce escolheu o mousse")
caso 2
escreval ("voce escolheu o sorvete")
caso 3
escreval ("voce escolheu o milkshake")
caso 4
escreval ("voce escolheu o sunday")

outrocaso
escreval("pedido incorreto")
fimescolha


Fimalgoritmo